language: ruby

cache:
  bundler: true

before_install:
  - gem install bundler
  - "rm ${BUNDLE_GEMFILE}.lock"

before_script:
  - bundle update
  - bundle exec "rake db:migrate RAILS_ENV=test"
  - export SECRET_KEY_BASE=rake secret

rvm:
- 2.2.4
- 2.3.0

notifications:
  email: false