language: ruby

before_install:
  - gem install bundler
  - "rm ${BUNDLE_GEMFILE}.lock"

before_script:
  - bundle update
  - bin/rake db:migrate RAILS_ENV=test

rvm:
- 2.2.4

notifications:
  email: false